version: "3.8"

services: 
  social-network:
    build: 
      context: .
      dockerfile: SocialNetworkBE/Dockerfile
    ports: 
      - ${ENV_PORT}:${ENV_PORT}
    volumes: 
      - ./SocialNetworkBE:/app
      - ./SocialNetworkFE/dist/social-network:/app/public
    depends_on: 
      - mysql_server  

  mysql_server:
    image: mysql:8.0
    ports: 
      - '$MYSQL_TCP_PORT:$MYSQL_TCP_PORT'
    expose:
      - '$MYSQL_TCP_PORT'  
    environment: 
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_TCP_PORT
